version: "2"
services:
    hass:
        image: homeassistant/home-assistant:stable
        network_mode: host
        restart: always
        volumes:
            - HASS_CONFIG:/config
        environment:
            TZ: America/New_York
    nodered:
        image: nodered/node-red
        ports:
            - 1880:1880
        volumes:
            - NODE_RED:/data
        environment:
            TZ: America/New_York
        